### PR TITLE
Update ingress to dynamically set service port based on httpsPort availability.

### PR DESCRIPTION
**Pull request by vgwizardx**
- Dynamically set service port based on httpsPort availability in ingress.yaml.

### CODE REVIEW

**Comment by vgwizardx** [comment]
This fixes an issue when you set up https because it couldn't get the httpsPort value.

**Review by markphelps — APPROVED** [review]
Thank you!🙏🏻

**Comment by virelu** [comment]
Hello @vgwizardx, 
I just updated my helm chart to v0.77.2 and I my configuration for using the httpPort does not work anymore.
If both ".Values.service.httpPort" and ".Values.service.httpsPort" are set, it always uses the httpsPort.

If I try to explicitly unset ".Values.service.httpsPort" using null or an empty string, I get an error during installation:
```console
Error: INSTALLATION FAILED: 1 error occurred:
        * Service "flipt" is invalid: spec.ports[1].port: Invalid value: 0: must be between 1 and 65535, inclusive
```
Is there a way to explicitly unset the httpsPort so the httpPort is used?

I would appreciate any help,
Thanks!

**Comment by vgwizardx** [comment]
@virelu Have you tried completely removing Values.service.httpsPort?
`service:
  enabled: true
  type: ClusterIP
  httpPort: 8080
  ## httpsPort: 443
  grpcPort: 9000`

**Comment by virelu** [comment]
@vgwizardx Yes I've tried this and it does not seem to work. The ingress still takes the default httpsPort 443. 
Does this config work for you?

**Comment by vgwizardx** [comment]
> @vgwizardx Yes I've tried this and it does not seem to work. The ingress still takes the default httpsPort 443. Does this config work for you?

@virelu  Looking at the chart; you must have port 443 passed somewhere else because 443 isn't in the chart as a default. The line of code I added will only grab the httpsPort if it exists. When I changed the port to only HTTP. It worked on my end. But I will be honest I'm not a K8s expert. I just noticed we weren't setting the https value when it was provided in the service.

**Comment by virelu** [comment]
@vgwizardx The default httpsPort value 443 is set [here](https://github.com/flipt-io/helm-charts/blob/48531f94e3add6aa1ae58edd3bb0a16edf350fd3/charts/flipt/values.yaml#L67). 
But just to be 100% sure I've used a fresh and empty cluster for installation, which yielded the same result as before. 
So right now it seems like I'm not able to use the httpPort at all for the ingress, since the httpsPort is always set.

**Comment by vgwizardx** [comment]
@virelu  You need to remove that line entirely from the values.yaml. The way it is setup is if you are passing httpsPort it will default to it. If that line does not exist meaning removed completely and not httpsPort : "" or httpsPort : null. Then it should only use the httpPort.

**Comment by erwan-b** [comment]
@vgwizardx , @virelu is right. The chart's default value set `httpsPort`  to 443.
Therefore, this value will be always set by default and the ingress will always use the service's https port.

I also want my ingress to use the http not https port. Working on a patch.

**Comment by vgwizardx** [comment]
> @vgwizardx , @virelu is right. The chart's default value set `httpsPort` to 443. Therefore, this value will be always set by default and the ingress will always use the service's https port.
> 
> I also want my ingress to use the http not https port. Working on a patch.

Could you share your values.yaml just the section with the ports. I want to see how you have it setup. 

from my understanding this is how it should work 

`default DEFAULT_VALUE GIVEN_VALUE` So if Given value doesn't exist it just uses the default value which is httpPort. 

`{{- $svcPort := default .Values.service.httpPort .Values.service.httpsPort -}}`

So you should have a httpsPort: null  in  your values yaml.

**Comment by erwan-b** [comment]
I create an issue, #209 about it.

de function default work perfectly fin. The problem comes from the service giving an error if the httpsPort value is set to null.

**Comment by vgwizardx** [comment]
> I create an issue, #209 about it.
> 
> your use of `default` function is perfectly fin. The problem comes from the service giving an error if the httpsPort value is set to null. Witch is mandatory because the default value.yaml set `httpsPort` to 443.

So you get that error if you remove line 70 and all other https mentions in the values.ymal?

image

I only have HTTP and no https anywhere in the values.yaml I'm not getting an error. 
https://stackoverflow.com/questions/62430401/how-to-add-a-default-value-to-a-kubernetes-helm-template

**Comment by erwan-b** [comment]
Your case work if I  clone the helm chart and delete all mentions of https in the `values.yaml`, example:
```
helm upgrade --install  flipt ./flipt-helm-charts/charts/flipt 
```

But if I want to use the packaged helm chart pushed on the repo `https://helm.flipt.io`. 
I will be forced to use the default value.yaml (file in the `flipt-helm-chart` repo) and so the httpsPort value will be always set.  That's why I need to overwrite this value with a new values.yaml. 
If the value `httpsPort` is not set, the chart will use the default 443. And if I don't want it, i don't have other chose than set it to null. Witch create the bug. 

Example:
```
helm upgrade --install  flipt flipt/flipt -f values.yaml
```

values.yaml:
```
service:
  httpsPorts: null
```


All this come from the default values.yaml package with the chart. And because this port is set by the `service.httpPort` or  `service.httpsPort`. I created a PR that add a `ingress.serivcePort` value. This allow user to chose witch port to use on the service. 

 https://github.com/flipt-io/helm-charts/pull/210

**Comment by vgwizardx** [comment]
> Your case work if I clone the helm chart and delete all mentions of https in the `values.yaml`, example:
> 
> ```
> helm upgrade --install  flipt ./flipt-helm-charts/charts/flipt 
> ```
> 
> But if I want to use the packaged helm chart pushed on the repo `https://helm.flipt.io`. I will be forced to use the default value.yaml (file in the `flipt-helm-chart` repo) and so the httpsPort value will be always set. That's why I need to overwrite this value with a new values.yaml. If the value `httpsPort` is not set, the chart will use the default value, 443. And if I don't want it, i don't have other chose than set it to null. Witch create the bug.
> 
> Example:
> 
> ```
> helm upgrade --install  flipt flipt/flipt -f values.yaml
> ```
> 
> values.yaml:
> 
> ```
> service:
>   httpsPorts: null
> ```
> 
> All this come from the default values.yaml package with the chart. And because this port is set by the `service.httpPort` or `service.httpsPort`. I created a PR that add a `ingress.serivcePort` value. This allow user to chose witch port to use on the service.
> 
> #210

I guess the fix for me would have just been remove httpsPort from the default values yaml or switch 

`{{- $svcPort := default .Values.service.httpPort .Values.service.httpsPort -}} `

to

`{{- $svcPort := .Values.service.httpsPort default .Values.service.httpPort-}}`

If the goal is to make it so you don't have to change the default helm chart. But its merged already so no biggie. Just make sure the docs are updated as well because the site will need to have the new value updated.

**Pull request merged**
